#!/bin/bash

kubectl delete deployments nginx kube-cert-manager scheduler tls-app
kubectl delete certificates hightowerlabs-dot-com
kubectl delete thirdpartyresources certificate.stable.hightower.com
kubectl delete secrets hightowerlabs hightowerlabs.com
